import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./(components)/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
{/* className="overflow-hidden" */}

    <head >
      <title>Portfolio | Mohamed Wasil</title>
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
      <link rel="icon" href='./profile_logo.jpg' />
    </head>

      <body className={inter.className}>
        
        <Navbar />

        {children}
        
        </body>
    </html>
  );
}
